name: Merge to Main

on:
  workflow_run:
    workflows: ["PHP CI Workflow"]
    types:
      - completed

jobs:
  merge:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
      - name: Fetch main branch
        run: git fetch origin main

      - name: Merge feature branch to main
        run: |
          branch_name=${{ github.event.workflow_run.head_branch }}
          git checkout main
          git merge origin/$branch_name
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
