name: PHP CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, dom, json

      - name: Install dependencies
        run: |
          composer install
          composer require --dev phpunit/phpunit

      - name: List files
        run: ls -la

      - name: Run PHPUnit tests
        run: |
          ./vendor/bin/phpunit --configuration phpunit.xml

      - name: Validate Composer configuration
        run: composer validate
